repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.0
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      -  id: black