---
name: "PyPI Release"

on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - 'v*'

jobs:
  pypi-publish:
    name: PyPI Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/django-typesense
    permissions:
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Upgrade Setuptools
        run: pip install --upgrade setuptools wheel

      - name: Build Distribution
        run: python setup.py sdist bdist_wheel --universal

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_AI_TOKEN }}
